Second batch replacing cfaforecastrenewalww
CDCgov/wastewater-informed-covid-forecasting pull request #163
Opened 2024-09-18 20:25 UTC by gvegayon

2024-09-20 19:14 UTC, gvegayon commented
Hey @kaitejohnson, this is ready for a run on Azure and your review.

2024-09-23 18:06 UTC, kaitejohnson requested changes
I am super lost what you changed here but when I try to build the container I get this error:

```
Error: stat /home/uox1/P/gh_repos/wastewater-informed-covid-forecasting/Dockerfile: no such file or directory
``` 

Something that used to point to the Containerfile got deleted or removed

2024-09-23 18:06 UTC, kaitejohnson commented on wweval/R/delay_distribs.R
> +#' @param mean_gi NEEDS DOCUMENTATION.
I think ultimately we wouldn't use these

2024-09-23 18:06 UTC, kaitejohnson commented on wweval/R/delay_distribs.R
> +#' @param neg_binom_mu NEEDS DOCUMENTATION.
These are documented in `wwinference`

2024-09-23 18:37 UTC, gvegayon commented
> Something that used to point to the Containerfile got deleted or removed? But I can't see that you changed anything in the setup_container.R. I checked and built the container in prod and it did work... 

I haven't changed that :S. I could try merging prod here and see if that fixes it?

2024-09-23 18:37 UTC, gvegayon commented on wweval/R/delay_distribs.R
> +#' @param mean_gi NEEDS DOCUMENTATION.
Which functions? All in `R/delay_distribs.R`?

2024-09-23 18:38 UTC, gvegayon commented on wweval/R/delay_distribs.R
> +#' @param neg_binom_mu NEEDS DOCUMENTATION.
Same question here.

2024-09-23 19:13 UTC, kaitejohnson commented on wweval/R/delay_distribs.R
> +#' @param mean_gi NEEDS DOCUMENTATION.
The only ones that are actually being used are in here! There are lots in `cfaforecastrenewalww` that are not needed (also so many that are not documented) https://github.com/CDCgov/ww-inference-model/blob/65c358830b551c01cabe30c9a1a66a122128ea04/R/delay_distribs.R#L86

2024-09-23 19:13 UTC, kaitejohnson commented on wweval/R/delay_distribs.R
> +#' @param neg_binom_mu NEEDS DOCUMENTATION.
https://github.com/CDCgov/ww-inference-model/blob/65c358830b551c01cabe30c9a1a66a122128ea04/R/delay_distribs.R#L132

2024-09-23 19:14 UTC, kaitejohnson commented
> > Something that used to point to the Containerfile got deleted or removed? But I can't see that you changed anything in the setup_container.R. I checked and built the container in prod and it did work...
> 
> I haven't changed that :S. I could try merging prod here and see if that fixes it?

Ah yes we just need to merge prod! Because we added the Containerfile to git, its git tracked so is no longer showing up when I switch branches https://github.com/CDCgov/wastewater-informed-covid-forecasting/blob/prod/Containerfile

2024-10-21 20:43 UTC, kaitejohnson commented
Closing with #182

2024-10-21 20:43 UTC, closed without merging