update from June codebase
CDCgov/wastewater-informed-covid-forecasting pull request #26
Opened 2024-06-04 20:50 UTC by kaitejohnson

Updating with most recent codebase on the development repo. Major changes include:
- additional site-to-state R(t) autoregulation coefficient priors (`autoreg_rt_site_a`, `autoreg_rt_site_b`)
- lots of evaluation functionality
- updates to cmdstan (requires 2.35.0 or greater) + updates to cmdstanr

2024-06-04 20:58 UTC, dylanhmorris requested changes
Need to remove accidentally committed binaries.

2024-06-04 20:58 UTC, dylanhmorris commented on cfaforecastrenewalww/inst/stan/renewal_ww_hosp_site_level_inf_dynamics
looks like a binary was accidentally committed

2024-06-04 20:58 UTC, dylanhmorris commented on cfaforecastrenewalww/inst/stan/renewal_ww_hosp
accidentally committed binary

2024-06-05 12:20 UTC, kaitejohnson commented on cfaforecastrenewalww/inst/stan/renewal_ww_hosp
removed! My bad

2024-06-05 16:11 UTC, dylanhmorris approved these changes
LGTM

2024-06-05 16:12 UTC, merged